{{- if .Values.continuedev.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-workspace.continueConfigName" . }}
  {{- if eq .Values.editor.type "devspace" }}
  namespace: {{ .Values.devspacesNamespace }}
  {{- end }}
  labels:
    {{- include "ai-workspace.labels" . | nindent 4 }}
data:
  config.yaml: |
    name: RHOAI Coding Agent
    version: 1.0.0
    schema: v1
    models:
      - name: {{ include "ai-workspace.modelDisplayName" . | trim }}
        provider: openai
        model: {{ .Values.aiModel.name }}
        {{- if eq .Values.editor.type "devspace" }}
        apiBase: http://{{ .Values.aiModel.name }}-predictor.{{ .Values.username }}-ai-ws.svc.cluster.local:8080/v1
        {{- else }}
        apiBase: http://{{ .Values.aiModel.name }}-predictor:8080/v1
        {{- end }}
        apiKey: EMPTY
        roles:
          - chat
          - edit
          - apply
          - autocomplete
        capabilities:
          - tool_use
        defaultCompletionOptions:
          contextLength: {{ include "ai-workspace.modelContextLength" . | trim }}
          temperature: {{ .Values.continuedev.temperature }}
    context:
      - provider: file
      - provider: code
      - provider: diff
      - provider: terminal
{{- end }}

