apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "ai-workspace.namespace" . }}
  labels:
    argocd.argoproj.io/managed-by: {{ .Values.argocd.managedBy }}
    app.kubernetes.io/part-of: {{ if eq .Values.editor.type "devspace" }}che.eclipse.org{{ else }}ai-workspace{{ end }}
    ai-workspace/username: {{ .Values.username | quote }}
