{{- $ns := include "ai-workspace.namespace" . -}}
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: {{ $ns }}
  labels:
    {{- include "ai-workspace.labels" . | nindent 4 }}
    {{- if eq .Values.editor.type "devspace" }}
    app.kubernetes.io/part-of: che.eclipse.org
    {{- end }}
